/* soapBFGlobalServiceProxy.h
   Generated by gSOAP 2.8.1 from Betfair.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapBFGlobalServiceProxy_H
#define soapBFGlobalServiceProxy_H
#include "soapH.h"

class SOAP_CMAC BFGlobalServiceProxy : public soap
{ public:
	/// Endpoint URL of service 'BFGlobalServiceProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BFGlobalServiceProxy();
	/// Constructor with copy of another engine state
	BFGlobalServiceProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	BFGlobalServiceProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	BFGlobalServiceProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BFGlobalServiceProxy();
	/// Initializer used by constructors
	virtual	void BFGlobalServiceProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'login' (returns error code or SOAP_OK)
	virtual	int login(_ns2__login *ns2__login, _ns2__loginResponse *ns2__loginResponse);

	/// Web service operation 'retrieveLIMBMessage' (returns error code or SOAP_OK)
	virtual	int retrieveLIMBMessage(_ns2__retrieveLIMBMessage *ns2__retrieveLIMBMessage, _ns2__retrieveLIMBMessageResponse *ns2__retrieveLIMBMessageResponse);

	/// Web service operation 'submitLIMBMessage' (returns error code or SOAP_OK)
	virtual	int submitLIMBMessage(_ns2__submitLIMBMessage *ns2__submitLIMBMessage, _ns2__submitLIMBMessageResponse *ns2__submitLIMBMessageResponse);

	/// Web service operation 'logout' (returns error code or SOAP_OK)
	virtual	int logout(_ns2__logout *ns2__logout, _ns2__logoutResponse *ns2__logoutResponse);

	/// Web service operation 'keepAlive' (returns error code or SOAP_OK)
	virtual	int keepAlive(_ns2__keepAlive *ns2__keepAlive, _ns2__keepAliveResponse *ns2__keepAliveResponse);

	/// Web service operation 'getEvents' (returns error code or SOAP_OK)
	virtual	int getEvents(_ns2__getEvents *ns2__getEvents, _ns2__getEventsResponse *ns2__getEventsResponse);

	/// Web service operation 'getActiveEventTypes' (returns error code or SOAP_OK)
	virtual	int getActiveEventTypes(_ns2__getActiveEventTypes *ns2__getActiveEventTypes, _ns2__getActiveEventTypesResponse *ns2__getActiveEventTypesResponse);

	/// Web service operation 'getAllEventTypes' (returns error code or SOAP_OK)
	virtual	int getAllEventTypes(_ns2__getAllEventTypes *ns2__getAllEventTypes, _ns2__getAllEventTypesResponse *ns2__getAllEventTypesResponse);

	/// Web service operation 'getSubscriptionInfo' (returns error code or SOAP_OK)
	virtual	int getSubscriptionInfo(_ns2__getSubscriptionInfo *ns2__getSubscriptionInfo, _ns2__getSubscriptionInfoResponse *ns2__getSubscriptionInfoResponse);

	/// Web service operation 'depositFromPaymentCard' (returns error code or SOAP_OK)
	virtual	int depositFromPaymentCard(_ns2__depositFromPaymentCard *ns2__depositFromPaymentCard, _ns2__depositFromPaymentCardResponse *ns2__depositFromPaymentCardResponse);

	/// Web service operation 'addPaymentCard' (returns error code or SOAP_OK)
	virtual	int addPaymentCard(_ns2__addPaymentCard *ns2__addPaymentCard, _ns2__addPaymentCardResponse *ns2__addPaymentCardResponse);

	/// Web service operation 'deletePaymentCard' (returns error code or SOAP_OK)
	virtual	int deletePaymentCard(_ns2__deletePaymentCard *ns2__deletePaymentCard, _ns2__deletePaymentCardResponse *ns2__deletePaymentCardResponse);

	/// Web service operation 'updatePaymentCard' (returns error code or SOAP_OK)
	virtual	int updatePaymentCard(_ns2__updatePaymentCard *ns2__updatePaymentCard, _ns2__updatePaymentCardResponse *ns2__updatePaymentCardResponse);

	/// Web service operation 'getPaymentCard' (returns error code or SOAP_OK)
	virtual	int getPaymentCard(_ns2__getPaymentCard *ns2__getPaymentCard, _ns2__getPaymentCardResponse *ns2__getPaymentCardResponse);

	/// Web service operation 'withdrawToPaymentCard' (returns error code or SOAP_OK)
	virtual	int withdrawToPaymentCard(_ns2__withdrawToPaymentCard *ns2__withdrawToPaymentCard, _ns2__withdrawToPaymentCardResponse *ns2__withdrawToPaymentCardResponse);

	/// Web service operation 'selfExclude' (returns error code or SOAP_OK)
	virtual	int selfExclude(_ns2__selfExclude *ns2__selfExclude, _ns2__selfExcludeResponse *ns2__selfExcludeResponse);

	/// Web service operation 'convertCurrency' (returns error code or SOAP_OK)
	virtual	int convertCurrency(_ns2__convertCurrency *ns2__convertCurrency, _ns2__convertCurrencyResponse *ns2__convertCurrencyResponse);

	/// Web service operation 'getAllCurrencies' (returns error code or SOAP_OK)
	virtual	int getAllCurrencies(_ns2__getAllCurrencies *ns2__getAllCurrencies, _ns2__getAllCurrenciesResponse *ns2__getAllCurrenciesResponse);

	/// Web service operation 'getAllCurrenciesV2' (returns error code or SOAP_OK)
	virtual	int getAllCurrenciesV2(_ns2__getAllCurrenciesV2 *ns2__getAllCurrenciesV2, _ns2__getAllCurrenciesV2Response *ns2__getAllCurrenciesV2Response);

	/// Web service operation 'viewReferAndEarn' (returns error code or SOAP_OK)
	virtual	int viewReferAndEarn(_ns2__viewReferAndEarn *ns2__viewReferAndEarn, _ns2__viewReferAndEarnResponse *ns2__viewReferAndEarnResponse);

	/// Web service operation 'viewProfile' (returns error code or SOAP_OK)
	virtual	int viewProfile(_ns2__viewProfile *ns2__viewProfile, _ns2__viewProfileResponse *ns2__viewProfileResponse);

	/// Web service operation 'viewProfileV2' (returns error code or SOAP_OK)
	virtual	int viewProfileV2(_ns2__viewProfileV2 *ns2__viewProfileV2, _ns2__viewProfileV2Response *ns2__viewProfileV2Response);

	/// Web service operation 'modifyProfile' (returns error code or SOAP_OK)
	virtual	int modifyProfile(_ns2__modifyProfile *ns2__modifyProfile, _ns2__modifyProfileResponse *ns2__modifyProfileResponse);

	/// Web service operation 'createAccount' (returns error code or SOAP_OK)
	virtual	int createAccount(_ns2__createAccount *ns2__createAccount, _ns2__createAccountResponse *ns2__createAccountResponse);

	/// Web service operation 'forgotPassword' (returns error code or SOAP_OK)
	virtual	int forgotPassword(_ns2__forgotPassword *ns2__forgotPassword, _ns2__forgotPasswordResponse *ns2__forgotPasswordResponse);

	/// Web service operation 'modifyPassword' (returns error code or SOAP_OK)
	virtual	int modifyPassword(_ns2__modifyPassword *ns2__modifyPassword, _ns2__modifyPasswordResponse *ns2__modifyPasswordResponse);

	/// Web service operation 'withdrawByBankTransfer' (returns error code or SOAP_OK)
	virtual	int withdrawByBankTransfer(_ns2__withdrawByBankTransfer *ns2__withdrawByBankTransfer, _ns2__withdrawByBankTransferResponse *ns2__withdrawByBankTransferResponse);

	/// Web service operation 'setChatName' (returns error code or SOAP_OK)
	virtual	int setChatName(_ns2__setChatName *ns2__setChatName, _ns2__setChatNameResponse *ns2__setChatNameResponse);

	/// Web service operation 'transferFunds' (returns error code or SOAP_OK)
	virtual	int transferFunds(_ns2__transferFunds *ns2__transferFunds, _ns2__transferFundsResponse *ns2__transferFundsResponse);
};
#endif
