/* soapBFExchangeServiceProxy.h
   Generated by gSOAP 2.8.1 from Betfair.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL OR Genivia's license for commercial use.
*/

#ifndef soapBFExchangeServiceProxy_H
#define soapBFExchangeServiceProxy_H
#include "soapH.h"

class SOAP_CMAC BFExchangeServiceProxy : public soap
{ public:
	/// Endpoint URL of service 'BFExchangeServiceProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BFExchangeServiceProxy();
	/// Constructor with copy of another engine state
	BFExchangeServiceProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	BFExchangeServiceProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	BFExchangeServiceProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BFExchangeServiceProxy();
	/// Initializer used by constructors
	virtual	void BFExchangeServiceProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getAccountFunds' (returns error code or SOAP_OK)
	virtual	int getAccountFunds(_ns4__getAccountFunds *ns4__getAccountFunds, _ns4__getAccountFundsResponse *ns4__getAccountFundsResponse);

	/// Web service operation 'cancelBets' (returns error code or SOAP_OK)
	virtual	int cancelBets(_ns4__cancelBets *ns4__cancelBets, _ns4__cancelBetsResponse *ns4__cancelBetsResponse);

	/// Web service operation 'cancelBetsByMarket' (returns error code or SOAP_OK)
	virtual	int cancelBetsByMarket(_ns4__cancelBetsByMarket *ns4__cancelBetsByMarket, _ns4__cancelBetsByMarketResponse *ns4__cancelBetsByMarketResponse);

	/// Web service operation 'updateBets' (returns error code or SOAP_OK)
	virtual	int updateBets(_ns4__updateBets *ns4__updateBets, _ns4__updateBetsResponse *ns4__updateBetsResponse);

	/// Web service operation 'placeBets' (returns error code or SOAP_OK)
	virtual	int placeBets(_ns4__placeBets *ns4__placeBets, _ns4__placeBetsResponse *ns4__placeBetsResponse);

	/// Web service operation 'getMarket' (returns error code or SOAP_OK)
	virtual	int getMarket(_ns4__getMarket *ns4__getMarket, _ns4__getMarketResponse *ns4__getMarketResponse);

	/// Web service operation 'getMarketInfo' (returns error code or SOAP_OK)
	virtual	int getMarketInfo(_ns4__getMarketInfo *ns4__getMarketInfo, _ns4__getMarketInfoResponse *ns4__getMarketInfoResponse);

	/// Web service operation 'getMarketPrices' (returns error code or SOAP_OK)
	virtual	int getMarketPrices(_ns4__getMarketPrices *ns4__getMarketPrices, _ns4__getMarketPricesResponse *ns4__getMarketPricesResponse);

	/// Web service operation 'getCompleteMarketPricesCompressed' (returns error code or SOAP_OK)
	virtual	int getCompleteMarketPricesCompressed(_ns4__getCompleteMarketPricesCompressed *ns4__getCompleteMarketPricesCompressed, _ns4__getCompleteMarketPricesCompressedResponse *ns4__getCompleteMarketPricesCompressedResponse);

	/// Web service operation 'getMarketTradedVolumeCompressed' (returns error code or SOAP_OK)
	virtual	int getMarketTradedVolumeCompressed(_ns4__getMarketTradedVolumeCompressed *ns4__getMarketTradedVolumeCompressed, _ns4__getMarketTradedVolumeCompressedResponse *ns4__getMarketTradedVolumeCompressedResponse);

	/// Web service operation 'getMarketPricesCompressed' (returns error code or SOAP_OK)
	virtual	int getMarketPricesCompressed(_ns4__getMarketPricesCompressed *ns4__getMarketPricesCompressed, _ns4__getMarketPricesCompressedResponse *ns4__getMarketPricesCompressedResponse);

	/// Web service operation 'getAllMarkets' (returns error code or SOAP_OK)
	virtual	int getAllMarkets(_ns4__getAllMarkets *ns4__getAllMarkets, _ns4__getAllMarketsResponse *ns4__getAllMarketsResponse);

	/// Web service operation 'getInPlayMarkets' (returns error code or SOAP_OK)
	virtual	int getInPlayMarkets(_ns4__getInPlayMarkets *ns4__getInPlayMarkets, _ns4__getInPlayMarketsResponse *ns4__getInPlayMarketsResponse);

	/// Web service operation 'getPrivateMarkets' (returns error code or SOAP_OK)
	virtual	int getPrivateMarkets(_ns4__getPrivateMarkets *ns4__getPrivateMarkets, _ns4__getPrivateMarketsResponse *ns4__getPrivateMarketsResponse);

	/// Web service operation 'getCurrentBets' (returns error code or SOAP_OK)
	virtual	int getCurrentBets(_ns4__getCurrentBets *ns4__getCurrentBets, _ns4__getCurrentBetsResponse *ns4__getCurrentBetsResponse);

	/// Web service operation 'getCoupon' (returns error code or SOAP_OK)
	virtual	int getCoupon(_ns4__getCoupon *ns4__getCoupon, _ns4__getCouponResponse *ns4__getCouponResponse);

	/// Web service operation 'getCurrentBetsLite' (returns error code or SOAP_OK)
	virtual	int getCurrentBetsLite(_ns4__getCurrentBetsLite *ns4__getCurrentBetsLite, _ns4__getCurrentBetsLiteResponse *ns4__getCurrentBetsLiteResponse);

	/// Web service operation 'getMUBets' (returns error code or SOAP_OK)
	virtual	int getMUBets(_ns4__getMUBets *ns4__getMUBets, _ns4__getMUBetsResponse *ns4__getMUBetsResponse);

	/// Web service operation 'getMUBetsLite' (returns error code or SOAP_OK)
	virtual	int getMUBetsLite(_ns4__getMUBetsLite *ns4__getMUBetsLite, _ns4__getMUBetsLiteResponse *ns4__getMUBetsLiteResponse);

	/// Web service operation 'getDetailAvailableMktDepth' (returns error code or SOAP_OK)
	virtual	int getDetailAvailableMktDepth(_ns4__getDetailAvailableMktDepth *ns4__getDetailAvailableMktDepth, _ns4__getDetailAvailableMktDepthResponse *ns4__getDetailAvailableMktDepthResponse);

	/// Web service operation 'getMarketTradedVolume' (returns error code or SOAP_OK)
	virtual	int getMarketTradedVolume(_ns4__getMarketTradedVolume *ns4__getMarketTradedVolume, _ns4__getMarketTradedVolumeResponse *ns4__getMarketTradedVolumeResponse);

	/// Web service operation 'getBetHistory' (returns error code or SOAP_OK)
	virtual	int getBetHistory(_ns4__getBetHistory *ns4__getBetHistory, _ns4__getBetHistoryResponse *ns4__getBetHistoryResponse);

	/// Web service operation 'getAccountStatement' (returns error code or SOAP_OK)
	virtual	int getAccountStatement(_ns4__getAccountStatement *ns4__getAccountStatement, _ns4__getAccountStatementResponse *ns4__getAccountStatementResponse);

	/// Web service operation 'getMarketProfitAndLoss' (returns error code or SOAP_OK)
	virtual	int getMarketProfitAndLoss(_ns4__getMarketProfitAndLoss *ns4__getMarketProfitAndLoss, _ns4__getMarketProfitAndLossResponse *ns4__getMarketProfitAndLossResponse);

	/// Web service operation 'getBet' (returns error code or SOAP_OK)
	virtual	int getBet(_ns4__getBet *ns4__getBet, _ns4__getBetResponse *ns4__getBetResponse);

	/// Web service operation 'getBetLite' (returns error code or SOAP_OK)
	virtual	int getBetLite(_ns4__getBetLite *ns4__getBetLite, _ns4__getBetLiteResponse *ns4__getBetLiteResponse);

	/// Web service operation 'getBetMatchesLite' (returns error code or SOAP_OK)
	virtual	int getBetMatchesLite(_ns4__getBetMatchesLite *ns4__getBetMatchesLite, _ns4__getBetMatchesLiteResponse *ns4__getBetMatchesLiteResponse);

	/// Web service operation 'getSilks' (returns error code or SOAP_OK)
	virtual	int getSilks(_ns4__getSilks *ns4__getSilks, _ns4__getSilksResponse *ns4__getSilksResponse);

	/// Web service operation 'getSilksV2' (returns error code or SOAP_OK)
	virtual	int getSilksV2(_ns4__getSilksV2 *ns4__getSilksV2, _ns4__getSilksV2Response *ns4__getSilksV2Response);

	/// Web service operation 'heartbeat' (returns error code or SOAP_OK)
	virtual	int heartbeat(_ns4__heartbeat *ns4__heartbeat, _ns4__heartbeatResponse *ns4__heartbeatResponse);
};
#endif
